spring.application.name=AAD-75

spring.datasource.url=jdbc:mysql://localhost:3306/AAD-75?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true